03 mongodb
Veronika-chenko/nodejs-course pull request #2
Opened 2022-12-30 20:24 UTC by Veronika-chenko

2022-12-31 09:14 UTC, KhYulian commented on server.js
> +start()
Можна скористатись IIFE

2022-12-31 09:15 UTC, KhYulian commented on src/controllers/contactsControllers.js
> +    if (!contact) return res.sendStatus(404)
res.status(404).json({message: "Contact not found"}) - поівдомлення не завадить, аналогічно в інших місцях

2022-12-31 09:15 UTC, KhYulian commented on src/controllers/contactsControllers.js
> +    if (!contactDelete) return res.sendStatus(404)
використовуйте фігурні дужки після if для кращої читабельності

2022-12-31 09:17 UTC, KhYulian requested changes
Потрібне доопрацювання

2022-12-31 09:18 UTC, KhYulian commented
Також подавайте в роботу в ЛМС, бо я можу пропустити ваш запит на ревю

2023-01-02 20:11 UTC, Veronika-chenko commented on server.js
> +start()
застосувала

2023-01-02 20:11 UTC, Veronika-chenko commented on src/controllers/contactsControllers.js
> +    if (!contact) return res.sendStatus(404)
повиправляла

2023-01-02 20:11 UTC, Veronika-chenko commented on src/controllers/contactsControllers.js
> +    if (!contactDelete) return res.sendStatus(404)
повиправляла

2023-01-02 20:52 UTC, KhYulian approved these changes
Чудова робота ❤️❤️

2023-01-02 20:53 UTC, merged