04 auth
Veronika-chenko/nodejs-course pull request #3
Opened 2023-01-10 22:27 UTC by Veronika-chenko

Перевір, будь ласка, код 
Із додаткових завдань зробила усі три. Єдине що, замість ,?page=1 робила ?skip=0; Сподіваюся, це ок?

2023-01-11 07:25 UTC, KhYulian commented on src/routes/middlewares/authMiddleware.js
> +            res.status(401).json({"message": "0 Not authorized"})
return

2023-01-11 07:27 UTC, KhYulian commented on src/routes/middlewares/authMiddleware.js
> +            next()
Якщо авторизація не пройшла успішно next можна викликати хібащо з помилкою. 
Або return res.status(401).json({"message": "0 Not authorized"}) або
return next(new MyError(401, "Not Authorized"))

2023-01-11 07:27 UTC, KhYulian commented on src/routes/middlewares/authMiddleware.js
> +            res.status(401).json({"message": "0 Not authorized"})
0?

2023-01-11 07:28 UTC, KhYulian commented on src/routes/middlewares/authMiddleware.js
> +            next()
Тут аналогічно

2023-01-11 07:28 UTC, KhYulian commented on src/routes/middlewares/subscriptionMiddleware.js
> +    subscriptionMiddleware: (req, res, next) => {
subscriptionValidation

2023-01-11 07:29 UTC, KhYulian commented on src/services/authService.js
> +    }
тут try catch не потрібен. Обробляйте помилки в контроллері

2023-01-11 07:29 UTC, KhYulian commented on src/services/authService.js
> +    }
Аналогічно в інших сервісах

2023-01-11 07:33 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-11 07:34 UTC, KhYulian commented
> Перевір, будь ласка, код Із додаткових завдань зробила усі три. Єдине що, замість ,?page=1 робила ?skip=0; Сподіваюся, це ок?
Загалом не дуже. skip ви вираховуєте на основі limit і page. skip = (page - 1) * limit;

2023-01-11 07:35 UTC, KhYulian commented
limit має мати якесь дефолтне значення, А в query має бути page та/або limit

2023-01-11 12:09 UTC, Veronika-chenko commented on src/routes/middlewares/subscriptionMiddleware.js
> +    subscriptionMiddleware: (req, res, next) => {
Що тут маєте на увазі?

2023-01-11 13:37 UTC, Veronika-chenko commented on src/routes/middlewares/authMiddleware.js
> +            res.status(401).json({"message": "0 Not authorized"})
+

2023-01-11 13:37 UTC, Veronika-chenko commented on src/routes/middlewares/authMiddleware.js
> +            next()
дякую, так, пропустила цей момент;
прибрала next() і переробила authMiddleware аналогічно до інших ф-цій міддлверів

2023-01-11 13:38 UTC, Veronika-chenko commented on src/routes/middlewares/authMiddleware.js
> +            res.status(401).json({"message": "0 Not authorized"})
+

2023-01-11 13:38 UTC, Veronika-chenko commented on src/routes/middlewares/authMiddleware.js
> +            next()
прибрала next()

2023-01-11 13:38 UTC, Veronika-chenko commented on src/services/authService.js
> +    }
прибрала try..catch в усіх сервісах

2023-01-11 13:38 UTC, Veronika-chenko commented
переробила пагінацію з використанням page i limit з req.query

2023-01-12 08:46 UTC, KhYulian commented
Не забувайте здавати роботу в лмс)

2023-01-12 12:45 UTC, KhYulian approved these changes
Чудова робота :heart:

2023-01-12 12:45 UTC, merged